repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'echo "Running TruffleHog"; trufflehog filesystem trufflehog-rules.yaml .'
        language: system
        stages: ["commit", "push"]
