name: Check sensitive info

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
          path: ./
          base: "$***REMOVED******REMOVED*** github.event.pull_request.base.ref ***REMOVED******REMOVED***"
          head: "$***REMOVED******REMOVED*** github.event.pull_request.head.ref ***REMOVED******REMOVED***"
          extra_args: --debug

      - name: Scan Results Status
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
